meta_product_name: "Nufiu Jardinagem"
meta_title: "Nufiu - Jardinagem e Plantas Ornamentais"
meta_description: "Kokedamas, terrários, produtos e serviços de jardinagem para transformar o seu ambiente. Entregas no Rio de Janeiro."
meta_image: "Banner.png" # should exist in `app/assets/images/`
